name: magnifier
description: A Flutter Package that adds a Magnifying Glass to your App.
version: 0.0.5
repository: https://github.com/preetjdp/magnifier
homepage: https://github.com/preetjdp/magnifier

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
